### ISSUE TITLE
Error due to extension difference on `gulp.config`

### ISSUE THREAD

**Issue by reykjavikingur** [Atomic-Reactor/CLI#2]
If you have installed the CLI version 1.0.26 and set up a version of the toolkit that used `gulp.config.json`, and then you upgrade the CLI to version 1.1.*, you start to get errors when trying to run any command (e.g. `arcli --version`) because it's looking for `gulp.config.js`. You should bump the major version number, because that is a breaking change from previous versions of the CLI and/or Toolkit.

**Comment by camdagr8** [comment]
This is actually a bug left over from some testing and needs to be fixed. I'll work it out soon. Thanks.

**Comment by camdagr8** [comment]
Fixed in version 1.1.5
